nome = input('Digite o seu nome: ')
Num_a = input("Digite um número: ")
Num_b = input('Digite outro número: ')
print()
print()
print(nome,', você digitou os números ',Num_a,' e ',Num_b)
print()
print("Adição dos números:",float(Num_a) + float(Num_b))
print()
print('Subtração dos número:',float(Num_a) - float(Num_b))
print()
print('Divisão dos números:',float(Num_a) / float(Num_b))
print()
print('Multiplicação dos números:',float(Num_a) * float(Num_b))